export const ADDITEM = 'ADDITEM';
export const DELETEITEM = 'DELETEITEM';
export const UPDATEITEM = 'UPDATEITEM';
export const UPDATEUSER = 'UPDATEUSER';
export const QUANTITYCHANGE ='QUANTITYCHANGE';


